name: divinelearn
description: "A Frontend Flutter Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  from_css_color: 2.0.0
  intl: ^0.19.0
  timeago: ^3.1.0
  json_path: 0.6.2
  auto_size_text: 3.0.0
  page_transition: 2.1.0
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  expandable: ^5.0.1
  table_calendar: ^3.1.1
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3


flutter:


  uses-material-design: true


  assets:
    - assets/images/

